$schema: ./schema.json
required:
  meta:
    title: string
    slug: string
  mode: stage | map
  theme: string
stage:
  requiredWhenModeIsStage:
    steps:
      - layout: string
        components:
          - type: string
            content: string?
            props: object?
            style: object?
            build: number | sequential | object?
            enter: string?
            exit: string?
map:
  requiredWhenModeIsMap:
    clusters:
      - id: string
        layout: string
        components:
          - type: string
            props: object?
    canvas:
      spacing: number?
    navigation:
      sequence: string[]?
shared:
  background:
    type: string
    colorStops: string[]?
  backgroundSections:
    - match:
        stepRange: [number, number]?
        clusterIds: string[]?
        group: string?
      shader: object
