/* Auto-generated by scripts/generate-registries.mjs. */

export const presentationComponentOverrides = {} satisfies Record<string, Record<string, unknown>>;

export const presentationLayoutOverrides = {} satisfies Record<string, Record<string, unknown>>;

export const presentationTransitionOverrides = {} satisfies Record<string, Record<string, unknown>>;
